# orbs:
#   react: thefrontside/react@0.2.0
# version: 2.1

# jobs:
#   test:
#     steps:
#       - checkout
# #    - run:
# #         name: Install
# #         command: yarn install
        
# workflows:
#   push:
#     jobs:
#      - test
      
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    executor:
      name: win/default 
      size: "medium"
    steps:
      - checkout
      - run: echo "this is the build job"

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
