# orbs:
#   react: thefrontside/react@0.2.0
version: 2.1

jobs:
  test:
    steps:
      - checkout
#    - run:
#         name: Install
#         command: yarn install
        
workflows:
  push:
    jobs:
     - test
